[Rubocop] updated to rubocop-0.49.1
umbrellio/code-style pull request #25
Opened 2017-05-31 20:34 UTC by JelF

All new features mentioned

2017-06-01 10:09 UTC, JelF commented
Should disable `Style/MultipleComparison` due to inconsistency between rails and non-rails

2017-06-01 10:10 UTC, tycooon commented on rubocop/lib/rubocop.rails.yml
> +Rails/ApplicationJob:
Вообще штука не лишняя.

2017-06-01 10:10 UTC, tycooon commented on rubocop/lib/rubocop.rails.yml
> +Rails/ApplicationRecord:
Как и эта.

2017-06-01 10:10 UTC, tycooon commented on rubocop/lib/rubocop.yml
> +  Enabled: false
А почему у нас это выключено?

2017-06-01 10:10 UTC, tycooon commented on rubocop/lib/rubocop.yml
> +Style/FormatStringToken:
Не понял что это.

2017-06-01 10:11 UTC, JelF commented on rubocop/lib/rubocop.yml
> +Style/FormatStringToken:
я тоже, буду смотреть на реальном коде

2017-06-01 10:11 UTC, JelF commented on rubocop/lib/rubocop.rails.yml
> +Rails/ApplicationJob:
+

2017-06-02 08:54 UTC, tycooon approved these changes

2017-06-02 08:58 UTC, TrumpClone commented on rubocop/lib/rubocop.yml
> +Style/FormatStringToken:
норм же, всегда строго указывать тип в formatted strings

2017-06-02 10:09 UTC, JelF commented on rubocop/lib/rubocop.yml
> +Style/FormatStringToken:
@TrumpClone 
Тут есть замечательная история, что у нас в ямле живет огромное число formatted_strings, которые абсолютно все используют %{}, например

2017-06-02 10:15 UTC, fiscal-cliff requested changes

2017-06-02 10:15 UTC, fiscal-cliff commented on rubocop/lib/rubocop.yml
> +Layout/MultilineOperationIndentation:
тоже полезный коп

2017-06-02 10:15 UTC, fiscal-cliff commented on rubocop/lib/rubocop.yml
> +Layout/SpaceInsideBrackets:
я б оставил

2017-06-02 10:15 UTC, fiscal-cliff commented on rubocop/lib/rubocop.yml
>  Lint/ShadowingOuterLocalVariable:
повышает читаемость

2017-06-02 10:18 UTC, JelF commented on rubocop/lib/rubocop.yml
> +Layout/SpaceInsideBrackets:
Я не менял, это ренейм

2017-06-02 10:18 UTC, JelF commented on rubocop/lib/rubocop.yml
>  Lint/ShadowingOuterLocalVariable:
Не относится к правкам в этом PR

2017-06-02 10:31 UTC, fiscal-cliff approved these changes

2017-06-02 10:33 UTC, merged